spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ENC(zFG6GJcYTTZ2IKl2cv/+sbLF2PBc5u9ugCfrGsRZ1MRkZxcLsb4oKCoo6eORZ/gdlk3lAZJXq9SXuqxM2dIU5YFwc37Hrjhna1Q7zYhmuWbkFXm4iTcduae/KfGgt/3h)
    username: ENC(FU4sLp0cpczGXqBP2/UfhQupodZ3hTGf)
    password: ENC(cbttnt+0rFJyWeHZDSxpZmsxmFuGsCQMPxtplnQoB+VW06gl9g7iDg==)
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      format_sql: true
      use_sql_comments: true


