spring:
  profiles:
    active:
      - prod
    group:
      develop:
        - develop
        - jwt
        - oauth
        - redis
        - youtube
      prod:
        - prod
        - oauth-prod
        - jwt
        - redis
        - youtube
      stage:
        - stage
        - oauth-prod
        - jwt
        - redis
        - youtube

server:
  port: 8082
