spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/whatsong
    maximum-pool-size: '4'
    username: root
    password: root1234
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      format_sql: true
      use_sql_comments: true

music_room:
  share:
    prefix: "http://localhost:8080/"