######################################################################
# PostgreSQL Settings
######################################################################
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/whatsong
    maximum-pool-size: '4'
    username: root
    password: root1234
######################################################################
# JPA Settings
######################################################################
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
