spring:
  web:
    cors:
      allowed-origins:
        - http://localhost:3000
        - https://whatsong.vercel.app
      allowed-methods: GET, POST, PUT, PATCH, DELETE, OPTIONS, HEAD
      allowed-headers: "*"
      allow-credentials: true
  profiles:
    active:
      - prod
    group:
      develop:
        - develop
        - jwt
        - oauth
        - redis
        - youtube
      prod:
        - prod
        - oauth-prod
        - jwt
        - redis
        - youtube
      stage:
        - stage
        - oauth-prod
        - jwt
        - redis
        - youtube

server:
  port: 8082

jasypt:
  encryptor:
    bean: jasyptStringEncryptor