######################################################################
# PostgreSQL Settings
######################################################################
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/whatsong
    maximum-pool-size: '4'
    username: root
    password: root1234
######################################################################
# JPA Settings
######################################################################
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
######################################################################
# MVC Settings
######################################################################
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
######################################################################
# security Settings
######################################################################
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: f51146cf3f9524ee8e1e4c32a3e9a5d2
            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email #?? ??
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id